/*
 * This file is generated by jOOQ.
 */
package com.my1rm.jooq.tables;


import com.my1rm.jooq.Indexes;
import com.my1rm.jooq.Keys;
import com.my1rm.jooq.My1rm;
import com.my1rm.jooq.tables.records.ExerciseRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Exercise extends TableImpl<ExerciseRecord> {

    private static final long serialVersionUID = 1844148657;

    /**
     * The reference instance of <code>my1rm.EXERCISE</code>
     */
    public static final Exercise EXERCISE = new Exercise();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExerciseRecord> getRecordType() {
        return ExerciseRecord.class;
    }

    /**
     * The column <code>my1rm.EXERCISE.ID</code>.
     */
    public final TableField<ExerciseRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>my1rm.EXERCISE.CREATED_AT</code>.
     */
    public final TableField<ExerciseRecord, Timestamp> CREATED_AT = createField("CREATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP.precision(6), this, "");

    /**
     * The column <code>my1rm.EXERCISE.GOAL</code>.
     */
    public final TableField<ExerciseRecord, Double> GOAL = createField("GOAL", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>my1rm.EXERCISE.NAME</code>.
     */
    public final TableField<ExerciseRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>my1rm.EXERCISE.USER_ID</code>.
     */
    public final TableField<ExerciseRecord, Long> USER_ID = createField("USER_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>my1rm.EXERCISE</code> table reference
     */
    public Exercise() {
        this(DSL.name("EXERCISE"), null);
    }

    /**
     * Create an aliased <code>my1rm.EXERCISE</code> table reference
     */
    public Exercise(String alias) {
        this(DSL.name(alias), EXERCISE);
    }

    /**
     * Create an aliased <code>my1rm.EXERCISE</code> table reference
     */
    public Exercise(Name alias) {
        this(alias, EXERCISE);
    }

    private Exercise(Name alias, Table<ExerciseRecord> aliased) {
        this(alias, aliased, null);
    }

    private Exercise(Name alias, Table<ExerciseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Exercise(Table<O> child, ForeignKey<O, ExerciseRecord> key) {
        super(child, key, EXERCISE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return My1rm.MY1RM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FKB0MWPNFMBFU2SO83PB9WAF0AO_INDEX_A, Indexes.PRIMARY_KEY_A);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ExerciseRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_A;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ExerciseRecord>> getKeys() {
        return Arrays.<UniqueKey<ExerciseRecord>>asList(Keys.CONSTRAINT_A);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ExerciseRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ExerciseRecord, ?>>asList(Keys.FKB0MWPNFMBFU2SO83PB9WAF0AO);
    }

    public User user() {
        return new User(this, Keys.FKB0MWPNFMBFU2SO83PB9WAF0AO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Exercise as(String alias) {
        return new Exercise(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Exercise as(Name alias) {
        return new Exercise(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Exercise rename(String name) {
        return new Exercise(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Exercise rename(Name name) {
        return new Exercise(name, null);
    }
}
