/*
 * This file is generated by jOOQ.
 */
package com.my1rm.jooq;


import com.my1rm.jooq.tables.Attempt;
import com.my1rm.jooq.tables.Exercise;
import com.my1rm.jooq.tables.Language;
import com.my1rm.jooq.tables.Season;
import com.my1rm.jooq.tables.Token;
import com.my1rm.jooq.tables.User;
import com.my1rm.jooq.tables.UserOption;
import com.my1rm.jooq.tables.records.AttemptRecord;
import com.my1rm.jooq.tables.records.ExerciseRecord;
import com.my1rm.jooq.tables.records.LanguageRecord;
import com.my1rm.jooq.tables.records.SeasonRecord;
import com.my1rm.jooq.tables.records.TokenRecord;
import com.my1rm.jooq.tables.records.UserOptionRecord;
import com.my1rm.jooq.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AttemptRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
    public static final UniqueKey<ExerciseRecord> CONSTRAINT_A = UniqueKeys0.CONSTRAINT_A;
    public static final UniqueKey<LanguageRecord> CONSTRAINT_C = UniqueKeys0.CONSTRAINT_C;
    public static final UniqueKey<SeasonRecord> CONSTRAINT_9 = UniqueKeys0.CONSTRAINT_9;
    public static final UniqueKey<TokenRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
    public static final UniqueKey<UserRecord> CONSTRAINT_27 = UniqueKeys0.CONSTRAINT_27;
    public static final UniqueKey<UserRecord> UK_OSO07PUDW19E66BS4YP8HWPUX = UniqueKeys0.UK_OSO07PUDW19E66BS4YP8HWPUX;
    public static final UniqueKey<UserOptionRecord> CONSTRAINT_D = UniqueKeys0.CONSTRAINT_D;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AttemptRecord, ExerciseRecord> FKCD2WCPCK3XOTL375KUYO4YB0U = ForeignKeys0.FKCD2WCPCK3XOTL375KUYO4YB0U;
    public static final ForeignKey<AttemptRecord, SeasonRecord> FKNQLYSVCHVYJ71W2EX1AQGX444 = ForeignKeys0.FKNQLYSVCHVYJ71W2EX1AQGX444;
    public static final ForeignKey<AttemptRecord, UserRecord> FKIERY2PPOLDI66OL7525EB1ADB = ForeignKeys0.FKIERY2PPOLDI66OL7525EB1ADB;
    public static final ForeignKey<ExerciseRecord, UserRecord> FKB0MWPNFMBFU2SO83PB9WAF0AO = ForeignKeys0.FKB0MWPNFMBFU2SO83PB9WAF0AO;
    public static final ForeignKey<SeasonRecord, UserRecord> FKTCL52SDGLRMC1JPTFMNCINK09 = ForeignKeys0.FKTCL52SDGLRMC1JPTFMNCINK09;
    public static final ForeignKey<TokenRecord, UserRecord> FKCR55UO5IEX6L1HS2XQP94G2SS = ForeignKeys0.FKCR55UO5IEX6L1HS2XQP94G2SS;
    public static final ForeignKey<UserOptionRecord, LanguageRecord> FK300INJW6I3MCW7FVRWO19P7Q5 = ForeignKeys0.FK300INJW6I3MCW7FVRWO19P7Q5;
    public static final ForeignKey<UserOptionRecord, UserRecord> FK2P5OTBGWV6TGF70068RSW2JNH = ForeignKeys0.FK2P5OTBGWV6TGF70068RSW2JNH;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AttemptRecord> CONSTRAINT_2 = Internal.createUniqueKey(Attempt.ATTEMPT, "CONSTRAINT_2", Attempt.ATTEMPT.ID);
        public static final UniqueKey<ExerciseRecord> CONSTRAINT_A = Internal.createUniqueKey(Exercise.EXERCISE, "CONSTRAINT_A", Exercise.EXERCISE.ID);
        public static final UniqueKey<LanguageRecord> CONSTRAINT_C = Internal.createUniqueKey(Language.LANGUAGE, "CONSTRAINT_C", Language.LANGUAGE.ID);
        public static final UniqueKey<SeasonRecord> CONSTRAINT_9 = Internal.createUniqueKey(Season.SEASON, "CONSTRAINT_9", Season.SEASON.ID);
        public static final UniqueKey<TokenRecord> CONSTRAINT_4 = Internal.createUniqueKey(Token.TOKEN, "CONSTRAINT_4", Token.TOKEN.ID);
        public static final UniqueKey<UserRecord> CONSTRAINT_27 = Internal.createUniqueKey(User.USER, "CONSTRAINT_27", User.USER.ID);
        public static final UniqueKey<UserRecord> UK_OSO07PUDW19E66BS4YP8HWPUX = Internal.createUniqueKey(User.USER, "UK_OSO07PUDW19E66BS4YP8HWPUX", User.USER.EMAIL);
        public static final UniqueKey<UserOptionRecord> CONSTRAINT_D = Internal.createUniqueKey(UserOption.USER_OPTION, "CONSTRAINT_D", UserOption.USER_OPTION.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AttemptRecord, ExerciseRecord> FKCD2WCPCK3XOTL375KUYO4YB0U = Internal.createForeignKey(com.my1rm.jooq.Keys.CONSTRAINT_A, Attempt.ATTEMPT, "FKCD2WCPCK3XOTL375KUYO4YB0U", Attempt.ATTEMPT.EXERCISE_ID);
        public static final ForeignKey<AttemptRecord, SeasonRecord> FKNQLYSVCHVYJ71W2EX1AQGX444 = Internal.createForeignKey(com.my1rm.jooq.Keys.CONSTRAINT_9, Attempt.ATTEMPT, "FKNQLYSVCHVYJ71W2EX1AQGX444", Attempt.ATTEMPT.SEASON_ID);
        public static final ForeignKey<AttemptRecord, UserRecord> FKIERY2PPOLDI66OL7525EB1ADB = Internal.createForeignKey(com.my1rm.jooq.Keys.CONSTRAINT_27, Attempt.ATTEMPT, "FKIERY2PPOLDI66OL7525EB1ADB", Attempt.ATTEMPT.USER_ID);
        public static final ForeignKey<ExerciseRecord, UserRecord> FKB0MWPNFMBFU2SO83PB9WAF0AO = Internal.createForeignKey(com.my1rm.jooq.Keys.CONSTRAINT_27, Exercise.EXERCISE, "FKB0MWPNFMBFU2SO83PB9WAF0AO", Exercise.EXERCISE.USER_ID);
        public static final ForeignKey<SeasonRecord, UserRecord> FKTCL52SDGLRMC1JPTFMNCINK09 = Internal.createForeignKey(com.my1rm.jooq.Keys.CONSTRAINT_27, Season.SEASON, "FKTCL52SDGLRMC1JPTFMNCINK09", Season.SEASON.USER_ID);
        public static final ForeignKey<TokenRecord, UserRecord> FKCR55UO5IEX6L1HS2XQP94G2SS = Internal.createForeignKey(com.my1rm.jooq.Keys.CONSTRAINT_27, Token.TOKEN, "FKCR55UO5IEX6L1HS2XQP94G2SS", Token.TOKEN.USER_ID);
        public static final ForeignKey<UserOptionRecord, LanguageRecord> FK300INJW6I3MCW7FVRWO19P7Q5 = Internal.createForeignKey(com.my1rm.jooq.Keys.CONSTRAINT_C, UserOption.USER_OPTION, "FK300INJW6I3MCW7FVRWO19P7Q5", UserOption.USER_OPTION.LANGUAGE_ID);
        public static final ForeignKey<UserOptionRecord, UserRecord> FK2P5OTBGWV6TGF70068RSW2JNH = Internal.createForeignKey(com.my1rm.jooq.Keys.CONSTRAINT_27, UserOption.USER_OPTION, "FK2P5OTBGWV6TGF70068RSW2JNH", UserOption.USER_OPTION.USER_ID);
    }
}
