/*
 * This file is generated by jOOQ.
 */
package com.my1rm.jooq;


import com.my1rm.jooq.tables.Attempt;
import com.my1rm.jooq.tables.Exercise;
import com.my1rm.jooq.tables.Language;
import com.my1rm.jooq.tables.Season;
import com.my1rm.jooq.tables.Token;
import com.my1rm.jooq.tables.User;
import com.my1rm.jooq.tables.UserOption;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class My1rm extends SchemaImpl {

    private static final long serialVersionUID = -1393850413;

    /**
     * The reference instance of <code>my1rm</code>
     */
    public static final My1rm MY1RM = new My1rm();

    /**
     * The table <code>my1rm.ATTEMPT</code>.
     */
    public final Attempt ATTEMPT = com.my1rm.jooq.tables.Attempt.ATTEMPT;

    /**
     * The table <code>my1rm.EXERCISE</code>.
     */
    public final Exercise EXERCISE = com.my1rm.jooq.tables.Exercise.EXERCISE;

    /**
     * The table <code>my1rm.LANGUAGE</code>.
     */
    public final Language LANGUAGE = com.my1rm.jooq.tables.Language.LANGUAGE;

    /**
     * The table <code>my1rm.SEASON</code>.
     */
    public final Season SEASON = com.my1rm.jooq.tables.Season.SEASON;

    /**
     * The table <code>my1rm.TOKEN</code>.
     */
    public final Token TOKEN = com.my1rm.jooq.tables.Token.TOKEN;

    /**
     * The table <code>my1rm.USER</code>.
     */
    public final User USER = com.my1rm.jooq.tables.User.USER;

    /**
     * The table <code>my1rm.USER_OPTION</code>.
     */
    public final UserOption USER_OPTION = com.my1rm.jooq.tables.UserOption.USER_OPTION;

    /**
     * No further instances allowed
     */
    private My1rm() {
        super("my1rm", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.HIBERNATE_SEQUENCE);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Attempt.ATTEMPT,
            Exercise.EXERCISE,
            Language.LANGUAGE,
            Season.SEASON,
            Token.TOKEN,
            User.USER,
            UserOption.USER_OPTION);
    }
}
